# Generated by Django 4.2.13 on 2024-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_content_ad_description_remove_ad_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/'),
        ),
    ]
